
### Registro
POST http://localhost:8080/api/v1/auth/register HTTP/1.1
content-type: application/json
Origin: http://localhost:3000

{
    "name": "João Pedro",
    "email": "joao@teste.com",
    "password": "27072001"
}

### Login
POST http://localhost:8080/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "email": "joao@teste.com",
    "password": "27072001"
}

### Todos usuários
GET http://localhost:8080/api/v1/users/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjOGMxODJlOS01ZDY2LTRhZDItYjgwZi0xYzRkZmVjYzAzYzQifQ.eyJleHAiOjE3NzUxMjQwOTgsImlhdCI6MTc3NTAzNzY5OCwianRpIjoiMzU3MGRlMDYtZmMxNi00NTAyLWIzYTUtYjhkN2FiZDBlZjEwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL21hc3RlciIsInR5cCI6IkluaXRpYWxBY2Nlc3NUb2tlbiJ9.N8jDB8B39ztsP_p_zy8W2wDXwiQw-ZgIL1TGbIqC7gi5zH-tIlujXHx4N7t5AP3FQkT-Q-RzLDXnxwB--tesog

### Busca um usuário
GET http://localhost:8080/api/v1/users/2 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInN1YiI6ImpvYW9AdGVzdGUuY29tIiwiZXhwIjoxNzcwMjgyNzMzfQ.U3bLGtzQceHwy3iI0QfwQvJoZ6I_XjUA-hIkiDnQLIg