spring.application.name=operix
spring.config.import=optional:dotenv:.env
server.ssl.enabled=false
server.port=8081

# Configuração do Resource Server (Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/operix
keycloak.admin-client-id=operix-sso
keycloak.admin-client-secret=R4Babm4EOQJVmhBkul0LhT3EfxBAy3vu
keycloak.realm=operix
keycloak.base-url=http://localhost:8080


# Datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/operixsso
spring.datasource.username=root
spring.datasource.password=root

# Logging
logging.level.org.springframework.security=info


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=false

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

